import { UserRole } from "@prisma/client";

export const PERMISSIONS = {
  TENANTS_CREATE: "tenants:create",
  TENANTS_LIST: "tenants:list",
  TENANTS_READ: "tenants:read",
  TENANTS_UPDATE: "tenants:update",
  USERS_CREATE: "users:create",
  USERS_LIST: "users:list",
  USERS_READ: "users:read",
  USERS_READ_SELF: "users:read:self",
  USERS_READ_MEMBERSHIPS: "users:read:memberships",
  USERS_UPDATE: "users:update",
  MEMBERSHIPS_CREATE: "memberships:create",
  MEMBERSHIPS_UPDATE: "memberships:update",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.TENANTS_CREATE,
    PERMISSIONS.TENANTS_LIST,
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.TENANTS_UPDATE,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_LIST,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.MEMBERSHIPS_CREATE,
    PERMISSIONS.MEMBERSHIPS_UPDATE,
  ],
  TENANT_ADMIN: [
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.TENANTS_UPDATE,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_LIST,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.MEMBERSHIPS_CREATE,
    PERMISSIONS.MEMBERSHIPS_UPDATE,
  ],
  PRINCIPAL: [
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
  COORDINATOR: [
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
  SECRETARY: [
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
  TEACHER: [PERMISSIONS.USERS_READ_SELF, PERMISSIONS.USERS_READ_MEMBERSHIPS],
  GUARDIAN: [PERMISSIONS.USERS_READ_SELF, PERMISSIONS.USERS_READ_MEMBERSHIPS],
  STUDENT: [PERMISSIONS.USERS_READ_SELF, PERMISSIONS.USERS_READ_MEMBERSHIPS],
  SUPPORT_AGENT: [
    PERMISSIONS.TENANTS_LIST,
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
};

export function getPermissionsForRole(role: UserRole) {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(role: UserRole, permission: string) {
  return getPermissionsForRole(role).includes(permission as Permission);
}
