import { UserRole } from "@prisma/client";

export const PERMISSIONS = {
  TENANTS_LIST: "tenants:list",
  TENANTS_READ: "tenants:read",
  USERS_READ_SELF: "users:read:self",
  USERS_READ_MEMBERSHIPS: "users:read:memberships",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.TENANTS_LIST,
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
  TENANT_ADMIN: [
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
  PRINCIPAL: [
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
  COORDINATOR: [
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
  SECRETARY: [
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
  TEACHER: [PERMISSIONS.USERS_READ_SELF, PERMISSIONS.USERS_READ_MEMBERSHIPS],
  GUARDIAN: [PERMISSIONS.USERS_READ_SELF, PERMISSIONS.USERS_READ_MEMBERSHIPS],
  STUDENT: [PERMISSIONS.USERS_READ_SELF, PERMISSIONS.USERS_READ_MEMBERSHIPS],
  SUPPORT_AGENT: [
    PERMISSIONS.TENANTS_LIST,
    PERMISSIONS.TENANTS_READ,
    PERMISSIONS.USERS_READ_SELF,
    PERMISSIONS.USERS_READ_MEMBERSHIPS,
  ],
};

export function getPermissionsForRole(role: UserRole) {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(role: UserRole, permission: string) {
  return getPermissionsForRole(role).includes(permission as Permission);
}
